alias br="git branch"
alias stash="git stash"
alias pop="git stash pop"
alias list="git stash list"
alias drop="git stash drop"
# Sync branch from remote
alias sync="git fetch --prune"

function gdiff() {
  if [ $# -eq 0 ]
  then
    git diff -w
  else
    git diff -w $1
  fi
}

function push() {
  remote="${ORIGIN:-origin}"
  current_branch=$(git symbolic-ref --quiet --short HEAD)
  branch=""
  push_flags=()

  for arg in "$@"; do
    case "$arg" in
      -*)
        push_flags+=("$arg")
        ;;
      *)
        if [ -z "$branch" ]; then
          branch="$arg"
        else
          echo "Unexpected extra argument: $arg"
          return 1
        fi
        ;;
    esac
  done

  branch="${branch:-$current_branch}"

  if [ -z "$branch" ]; then
    echo "Could not determine branch to push."
    return 1
  fi

  echo "Pushing $branch to $remote"
  git push "${push_flags[@]}" "$remote" "$branch"
}

function pull() {
  remote="${ORIGIN:-origin}"
  current_branch=$(git symbolic-ref --quiet --short HEAD)
  branch="${1:-$current_branch}"

  if [ -z "$branch" ]; then
    echo "Could not determine branch to pull."
    return 1
  fi

  echo "Pulling $branch from $remote"
  git pull "$remote" "$branch"
}
